#!/usr/bin/env python3
"""Regenerate src/launch/pinyin_table.rs (pinyin initial letters per hanzi).

The table maps a CJK character to the first letters of every pinyin reading
it has (heteronyms included), so `apps` can match a name by its initials
acronym: 文件管理器 (wen jian guan li qi) -> wjglq.

Coverage: every character GB2312 can encode (levels 1 and 2), i.e. the set a
Chinese desktop application name is realistically written with, plus a small
extra list. Generated once and committed; runtime has no pinyin dependency.

Usage:
    python3 -m pip install pypinyin      # only needed to regenerate
    python3 scripts/gen-pinyin.py        # rewrites src/launch/pinyin_table.rs
"""

import os
import sys

MAX_READINGS = 3
LETTERS = [chr(ord("a") + i) for i in range(26)]

HEADER = """\
//! Pinyin initial letters per hanzi, grouped by letter.
//!
//! Generated by `scripts/gen-pinyin.py`; do not edit by hand. Each entry is
//! `(letter, characters)`: the character has a pinyin reading whose first
//! letter is `letter`. A character with several readings appears in several
//! groups (see `super::pinyin`), and one with none is absent.
"""


def gb2312_chars():
    """Every character GB2312 encodes (levels 1 and 2)."""
    chars = []
    for high in range(0xA1, 0xFF):
        for low in range(0xA1, 0xFF):
            try:
                chars.append(bytes([high, low]).decode("gb2312"))
            except UnicodeDecodeError:
                pass
    return chars


def readings(ch, pypinyin):
    """Pinyin initial letters of `ch`, most common reading first."""
    style = pypinyin.Style.FIRST_LETTER
    default = pypinyin.pinyin(ch, style=style)[0][0].lower()
    every = []
    for group in pypinyin.pinyin(ch, heteronym=True, style=style):
        for reading in group:
            letter = reading.lower()
            if letter in LETTERS and letter not in every:
                every.append(letter)
    if default in LETTERS:
        every = [default] + [l for l in every if l != default]
    return every[:MAX_READINGS]


def groups(chars, pypinyin):
    table = {letter: [] for letter in LETTERS}
    skipped = []
    for ch in chars:
        letters = readings(ch, pypinyin)
        if not letters:
            skipped.append(ch)
        for letter in letters:
            table[letter].append(ch)
    return table, skipped


def chunk(text, width):
    return [text[i : i + width] for i in range(0, len(text), width)]


def render(table):
    lines = [HEADER, "pub(super) const GROUPS: &[(char, &str)] = &["]
    for letter in LETTERS:
        chars = "".join(table[letter])
        parts = chunk(chars, 76)
        lines.append("    ('%s', concat!(" % (letter,))
        for i, part in enumerate(parts):
            comma = "" if i == len(parts) - 1 else ","
            lines.append('        "%s"%s' % (part, comma))
        lines.append("    )),")
    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def main():
    try:
        import pypinyin
    except ImportError:
        sys.exit("gen-pinyin: pypinyin is missing; python3 -m pip install pypinyin")

    chars = gb2312_chars()
    table, skipped = groups(chars, pypinyin)
    if skipped:
        print("gen-pinyin: no reading for %d chars: %s" % (len(skipped), "".join(skipped)))

    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    path = os.path.join(root, "src", "launch", "pinyin_table.rs")
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(render(table))
    print("gen-pinyin: %d chars -> %s" % (len(chars), os.path.relpath(path, root)))


if __name__ == "__main__":
    main()
